### PR TITLE
Implement remaining webaim recommendations

### PR DESCRIPTION
**Pull request by geokala**
These are based on accessibility recommendations from: https://wave.webaim.org/report#/https://2023.pyconuk.org/

### CODE REVIEW

**Comment by geokala** [comment]
There is an alert about the "Contact us" link on the sponsorship page being adjacent to an identical link (in the header), but there is a body of intervening text, and moving the text+links on the page around feels like it would decrease clarity in general, so I'm accepting that one.

**Comment by geokala** [comment]
There is an alert about the length of the alt-text on the CfP page, but on reading the alert it seems clear to me that we're not providing information in the alt text that goes beyond what is visible in the picture, and I feel the currently provided information is probably fine and in keeping with the general tone so I'm accepting those alerts.

**Comment by geokala** [comment]
The long alt-text and neighbouring redundant links alerts are also present for the 'Inclusion' page, but once again these feel reasonable in the context so will be left.

**Comment by doismellburning** [comment]
This is fantastic, thank you so much

**Pull request merged**
